### ISSUE TITLE
TypeError: QApplication(List[str]): not enough arguments

### ISSUE THREAD

**Issue by luizavolpi** [domstoppable/QuickCSF#6]
Hi there! 
I have been trying to run the QuickCSF but I have this error message:

~~~~
$ python -m QuickCSF.app
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/hgfs/Linux/QuickCSF/QuickCSF/app.py", line 30, in <module>
    app = QtWidgets.QApplication()
TypeError: QApplication(List[str]): not enough arguments
~~~~

Do you have any idea what have I been doing wrong? I've installed all dependencies including PyQt5 (when I google the error this seems to be the source? But I am not sure, I'm not very familiar with Python or building GUIs).

Thank you!

**Comment by domstoppable** [comment]
Seems to be a minor difference between PySide2 and PyQt5. Can you use PySide2 instead?

**Comment by luizavolpi** [comment]
Thank you for your response! Changing to PySide2 seems to fix this error. There is a new error message now, however, that traces back to the argparseqt that I am not sure how to fix. My argparseqt version is==0.3.2

~~~
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/hgfs/Linux/QuickCSF/QuickCSF/app.py", line 144, in <module>
    main()
  File "/mnt/hgfs/Linux/QuickCSF/QuickCSF/app.py", line 136, in main
    settings = getSettings()
  File "/mnt/hgfs/Linux/QuickCSF/QuickCSF/app.py", line 130, in getSettings
    settings = ui.getSettings(parser, settings, ['sessionID', 'distance_mm'])
  File "/mnt/hgfs/Linux/QuickCSF/QuickCSF/ui.py", line 148, in getSettings
    dialog = argparseqt.gui.ArgDialog(parser)
  File "/home/lpvolpi/.local/lib/python3.6/site-packages/argparseqt/gui.py", line 19, in __init__
    self.argparseWidget = ArgparseListWidget(self.argParser, orphanGroupName)
  File "/home/lpvolpi/.local/lib/python3.6/site-packages/argparseqt/gui.py", line 79, in __init__
    groupWidget.addArguments(arguments.values())
  File "/home/lpvolpi/.local/lib/python3.6/site-packages/argparseqt/gui.py", line 147, in addArguments
    widget = wrappedWidgets.makeWidget(argument, self)
  File "/home/lpvolpi/.local/lib/python3.6/site-packages/argparseqt/wrappedWidgets.py", line 69, in makeWidget
    elif dataType == list or typing.get_origin(dataType) == list:
AttributeError: module 'typing' has no attribute 'get_origin'
~~~

Thank you for your help!

**Comment by luizavolpi** [comment]
I have an update! I installed the specific lowest version required for argparseqt (version 0.2.1) and it worked! Thank you for the support!
